= Frequently Asked Questions

== I'm using default `Sonar Way` rules (with default `Sonar Way` profile). When I install a Creedengo plugin, are the new Creedengo rules applied?

When a Creedengo plugin is installed by the marketplace, the rules are immediately available on SonarQube.
You can find them if you go to "rules" tab, and select rules with tag `eco-design`.

However, Creedengo rules are *not* automatically added to an existing SonarQube profile.

If you want to use Creedengo rules (for one language for example), you have many ways to configure it:

* Create a new quality profile, then select all rules (Creedengo rules or not) that you wish to include in the new profile.
Finally use this new profile as "default" profile for the selected language or set a few projects to use this profile.

* *OR* use our script to create the kind of profile mentioned above (explanation here: xref:dev:howto.adoc#initialize-default-profile-for-creedengo-plugins[Initialize default profiles for `creedengo` plugins])...
+
[WARNING]
The newly created profile will be set as the default profile for your language!

* *OR* update one of your current used quality profiles to add the newly available Creedengo rules.
